import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

const myFont = localFont({ src: './ClashDisplay-Regular.woff2' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex flex-col justify-between items-center min-h-screen ${myFont.className}`}>
        <div className="w-[90%] max-w-[1440px]">
        {children}
        </div>
      </body>
    </html>
  );
}
